/**
 * MFP Card Manifest — Typed data for all 45 oracle cards.
 * Source: CARD_MANIFEST.json (v1.0.0, 2026-02-10)
 */

export interface Card {
  id: string;
  name: string;
  chapter: number;
  chapter_title: string;
  triptych_role: 'A' | 'B' | 'C';
  triptych_role_name: 'Concept' | 'Challenge' | 'Transcendence';
  theme: string;
  theme_icon: string;
  theme_color: string;
  type: 'Wisdom' | 'Reflection' | 'Poem' | 'Theme' | 'Legendary';
  rarity: 'Common' | 'Uncommon' | 'Rare' | 'Epic' | 'Legendary';
  rarity_stars: number;
  emotional_power: number;
  wisdom_cost: number;
  quote: string;
  reflection_prompt: string;
  art_direction: string;
}

export interface Chapter {
  number: number;
  title: string;
  theme: string;
  icon: string;
  color: string;
}

export const CHAPTERS: Chapter[] = [
  {number: 1, title: 'Our Passion in Life', theme: 'Passion', icon: '🔥', color: '#EF4444'},
  {number: 2, title: 'A Prudent Use of Our Limited Time', theme: 'Time', icon: '⏰', color: '#3B82F6'},
  {number: 3, title: 'Healing Our Brokenness', theme: 'Healing', icon: '💚', color: '#10B981'},
  {number: 4, title: 'Live in Freedom', theme: 'Freedom', icon: '🌬️', color: '#14B8A6'},
  {number: 5, title: 'Strive to Live a Transcendent Life', theme: 'Transcendence', icon: '✨', color: '#8B5CF6'},
  {number: 6, title: 'There is Hope in Everything', theme: 'Hope', icon: '⭐', color: '#A855F7'},
  {number: 7, title: 'Self-Confidence and Humility', theme: 'Confidence', icon: '☀️', color: '#F97316'},
  {number: 8, title: 'The Advantage of the Optimistic Mind', theme: 'Fulfillment', icon: '🌿', color: '#22C55E'},
  {number: 9, title: 'A Self-Fulfilled Life is Tantamount to Happiness', theme: 'Fulfillment', icon: '🍃', color: '#00CED1'},
  {number: 10, title: 'Attaining Our Highest Potentials', theme: 'Potential', icon: '🎯', color: '#60A5FA'},
  {number: 11, title: 'Equality Holds Peace and Justice', theme: 'Equality', icon: '⚖️', color: '#9370DB'},
  {number: 12, title: 'Forgiveness is the Most Effective Solution', theme: 'Forgiveness', icon: '💧', color: '#06B6D4'},
  {number: 13, title: 'Accountability is a Must', theme: 'Accountability', icon: '🛡️', color: '#EA580C'},
  {number: 14, title: 'Today is the First Day of Your Life', theme: 'Today', icon: '🌅', color: '#FBBF24'},
  {number: 15, title: 'Life is Longest', theme: 'Life', icon: '🌍', color: '#84CC16'},
];

export const CARDS: Card[] = [
  {id:"MFP-001",name:"The Spark",chapter:1,chapter_title:"Our Passion in Life",triptych_role:"A",triptych_role_name:"Concept",theme:"Passion",theme_icon:"🔥",theme_color:"#EF4444",type:"Wisdom",rarity:"Common",rarity_stars:1,emotional_power:35,wisdom_cost:1,quote:"What ignites the fire in your soul is the truest compass you'll ever hold.",reflection_prompt:"What activity or pursuit makes you lose track of time? When did you last feel truly alive?",art_direction:"Single bright spark, small and contained, parametric curves beginning to form"},
  {id:"MFP-002",name:"The Doubt",chapter:1,chapter_title:"Our Passion in Life",triptych_role:"B",triptych_role_name:"Challenge",theme:"Passion",theme_icon:"🔥",theme_color:"#EF4444",type:"Reflection",rarity:"Uncommon",rarity_stars:2,emotional_power:42,wisdom_cost:2,quote:"Every flame flickers before it roars. What makes you hesitate?",reflection_prompt:"What fear or doubt has held you back from pursuing what you love most?",art_direction:"Curves twist into turbulence, doubt, flickering energy — the flame threatened"},
  {id:"MFP-003",name:"The Flame",chapter:1,chapter_title:"Our Passion in Life",triptych_role:"C",triptych_role_name:"Transcendence",theme:"Passion",theme_icon:"🔥",theme_color:"#EF4444",type:"Poem",rarity:"Rare",rarity_stars:3,emotional_power:58,wisdom_cost:3,quote:"I am the fire that dances without fuel — passion sustained by purpose alone.",reflection_prompt:"Describe a moment when your passion overcame every obstacle in its path.",art_direction:"Curves explode outward into a full radiant flame-like form — passion fully realized"},
  {id:"MFP-004",name:"The Hourglass",chapter:2,chapter_title:"A Prudent Use of Our Limited Time",triptych_role:"A",triptych_role_name:"Concept",theme:"Time",theme_icon:"⏰",theme_color:"#3B82F6",type:"Wisdom",rarity:"Common",rarity_stars:1,emotional_power:30,wisdom_cost:1,quote:"Time is the one currency that cannot be earned back once spent.",reflection_prompt:"How did you spend your time today? Was it aligned with what matters most to you?",art_direction:"Hourglass-like form, curves flowing downward, measured and cosmic"},
  {id:"MFP-005",name:"The Distraction",chapter:2,chapter_title:"A Prudent Use of Our Limited Time",triptych_role:"B",triptych_role_name:"Challenge",theme:"Time",theme_icon:"⏰",theme_color:"#3B82F6",type:"Reflection",rarity:"Common",rarity_stars:1,emotional_power:28,wisdom_cost:1,quote:"What steals your hours without your permission?",reflection_prompt:"Name one habit that wastes your time. What would you replace it with?",art_direction:"Scattered, fragmented curves — time dispersed, distracted, broken flow"},
  {id:"MFP-006",name:"The Legacy",chapter:2,chapter_title:"A Prudent Use of Our Limited Time",triptych_role:"C",triptych_role_name:"Transcendence",theme:"Time",theme_icon:"⏰",theme_color:"#3B82F6",type:"Theme",rarity:"Rare",rarity_stars:3,emotional_power:55,wisdom_cost:3,quote:"The prudent use of a single day echoes through generations.",reflection_prompt:"What is one thing you could do today that your future self would thank you for?",art_direction:"Curves coalesce into an infinite spiral — time mastered, legacy forming"},
  {id:"MFP-007",name:"The Wound",chapter:3,chapter_title:"Healing Our Brokenness",triptych_role:"A",triptych_role_name:"Concept",theme:"Healing",theme_icon:"💚",theme_color:"#10B981",type:"Wisdom",rarity:"Common",rarity_stars:1,emotional_power:32,wisdom_cost:1,quote:"Every scar is proof that you survived what tried to break you.",reflection_prompt:"What is one experience that hurt you but ultimately made you stronger?",art_direction:"Fractured, broken curves with gaps — a wound in the parametric flow"},
  {id:"MFP-008",name:"The Numbness",chapter:3,chapter_title:"Healing Our Brokenness",triptych_role:"B",triptych_role_name:"Challenge",theme:"Healing",theme_icon:"💚",theme_color:"#10B981",type:"Reflection",rarity:"Uncommon",rarity_stars:2,emotional_power:40,wisdom_cost:2,quote:"What pain have you buried so deep it became invisible?",reflection_prompt:"Is there an emotion you've been avoiding? What would happen if you let yourself feel it?",art_direction:"Curves still broken but beginning to reach toward each other — tentative healing"},
  {id:"MFP-009",name:"The Mending",chapter:3,chapter_title:"Healing Our Brokenness",triptych_role:"C",triptych_role_name:"Transcendence",theme:"Healing",theme_icon:"💚",theme_color:"#10B981",type:"Poem",rarity:"Rare",rarity_stars:3,emotional_power:60,wisdom_cost:3,quote:"I stitch my fractures with golden thread — broken, and more beautiful for it.",reflection_prompt:"How has a past wound become a source of wisdom or compassion in your life?",art_direction:"Curves fused together with golden highlights at join points — kintsugi healing"},
  {id:"MFP-010",name:"The Cage",chapter:4,chapter_title:"Live in Freedom",triptych_role:"A",triptych_role_name:"Concept",theme:"Freedom",theme_icon:"🌬️",theme_color:"#14B8A6",type:"Wisdom",rarity:"Common",rarity_stars:1,emotional_power:33,wisdom_cost:1,quote:"The heaviest chains are the ones you forged yourself.",reflection_prompt:"What self-imposed limitation are you ready to release?",art_direction:"Curves constrained in a tight rectangular form — a cage of parametric lines"},
  {id:"MFP-011",name:"The Fear",chapter:4,chapter_title:"Live in Freedom",triptych_role:"B",triptych_role_name:"Challenge",theme:"Freedom",theme_icon:"🌬️",theme_color:"#14B8A6",type:"Reflection",rarity:"Uncommon",rarity_stars:2,emotional_power:38,wisdom_cost:2,quote:"What would you do tomorrow if nothing could hold you back?",reflection_prompt:"Name the one fear that, if conquered, would change everything for you.",art_direction:"Curves bending outward, straining against invisible boundaries"},
  {id:"MFP-012",name:"The Flight",chapter:4,chapter_title:"Live in Freedom",triptych_role:"C",triptych_role_name:"Transcendence",theme:"Freedom",theme_icon:"🌬️",theme_color:"#14B8A6",type:"Theme",rarity:"Uncommon",rarity_stars:2,emotional_power:48,wisdom_cost:2,quote:"Freedom is not the absence of walls — it is the presence of wings.",reflection_prompt:"Describe a moment when you felt completely free. What made it possible?",art_direction:"Curves burst free, spreading wide like wings — liberation in motion"},
  {id:"MFP-013",name:"The Ordinary",chapter:5,chapter_title:"Strive to Live a Transcendent Life",triptych_role:"A",triptych_role_name:"Concept",theme:"Transcendence",theme_icon:"✨",theme_color:"#8B5CF6",type:"Wisdom",rarity:"Common",rarity_stars:1,emotional_power:30,wisdom_cost:1,quote:"Transcendence begins the moment you refuse to accept the ceiling above you.",reflection_prompt:"What 'ordinary' aspect of your life are you ready to elevate?",art_direction:"Horizontal curves, grounded, ordinary — stable but flat"},
  {id:"MFP-014",name:"The Gravity",chapter:5,chapter_title:"Strive to Live a Transcendent Life",triptych_role:"B",triptych_role_name:"Challenge",theme:"Transcendence",theme_icon:"✨",theme_color:"#8B5CF6",type:"Reflection",rarity:"Common",rarity_stars:1,emotional_power:32,wisdom_cost:1,quote:"What keeps pulling you back to the ground when your soul wants to rise?",reflection_prompt:"What habit, relationship, or belief is weighing you down right now?",art_direction:"Curves pulling downward, weighted by gravity — heavy and grounded"},
  {id:"MFP-015",name:"The Ascension",chapter:5,chapter_title:"Strive to Live a Transcendent Life",triptych_role:"C",triptych_role_name:"Transcendence",theme:"Transcendence",theme_icon:"✨",theme_color:"#8B5CF6",type:"Poem",rarity:"Epic",rarity_stars:4,emotional_power:78,wisdom_cost:4,quote:"I have outgrown every box they built for me — my edges touch the infinite.",reflection_prompt:"What version of yourself have you outgrown? What's emerging in its place?",art_direction:"Curves ascending vertically, reaching upward into light, dissolving into starlike points"},
  {id:"MFP-016",name:"The Seed",chapter:6,chapter_title:"There is Hope in Everything",triptych_role:"A",triptych_role_name:"Concept",theme:"Hope",theme_icon:"⭐",theme_color:"#A855F7",type:"Wisdom",rarity:"Common",rarity_stars:1,emotional_power:28,wisdom_cost:1,quote:"Hope is the seed that grows in the darkest soil.",reflection_prompt:"What small hope are you nurturing right now, even in difficulty?",art_direction:"Tiny seedlike form, small curves curled inward — potential waiting"},
  {id:"MFP-017",name:"The Despair",chapter:6,chapter_title:"There is Hope in Everything",triptych_role:"B",triptych_role_name:"Challenge",theme:"Hope",theme_icon:"⭐",theme_color:"#A855F7",type:"Reflection",rarity:"Uncommon",rarity_stars:2,emotional_power:44,wisdom_cost:2,quote:"When everything falls apart, what is the one thing you still believe in?",reflection_prompt:"Think of your darkest moment. What pulled you through? What did you hold onto?",art_direction:"Darkness, sparse scattered curves — despair, emptiness"},
  {id:"MFP-018",name:"The Dawn",chapter:6,chapter_title:"There is Hope in Everything",triptych_role:"C",triptych_role_name:"Transcendence",theme:"Hope",theme_icon:"⭐",theme_color:"#A855F7",type:"Theme",rarity:"Epic",rarity_stars:4,emotional_power:72,wisdom_cost:4,quote:"After the longest night, the dawn does not ask permission to arrive.",reflection_prompt:"When has hope surprised you? Describe a time light appeared when you least expected it.",art_direction:"Curves opening like a sunrise, warmth radiating outward — dawn breaking"},
  {id:"MFP-019",name:"The Mirror",chapter:7,chapter_title:"Self-Confidence and Humility",triptych_role:"A",triptych_role_name:"Concept",theme:"Confidence",theme_icon:"☀️",theme_color:"#F97316",type:"Wisdom",rarity:"Common",rarity_stars:1,emotional_power:34,wisdom_cost:1,quote:"True confidence is not the absence of doubt — it is the mastery of it.",reflection_prompt:"What are you genuinely confident about? What makes you sure?",art_direction:"Reflective form, curves creating mirror-like symmetry — self-examination"},
  {id:"MFP-020",name:"The Ego",chapter:7,chapter_title:"Self-Confidence and Humility",triptych_role:"B",triptych_role_name:"Challenge",theme:"Confidence",theme_icon:"☀️",theme_color:"#F97316",type:"Reflection",rarity:"Common",rarity_stars:1,emotional_power:30,wisdom_cost:1,quote:"Where does your confidence end and your ego begin?",reflection_prompt:"When has your pride gotten in the way of growth or connection?",art_direction:"Curves inflating, overreaching — ego expanding beyond its bounds"},
  {id:"MFP-021",name:"The Balance",chapter:7,chapter_title:"Self-Confidence and Humility",triptych_role:"C",triptych_role_name:"Transcendence",theme:"Confidence",theme_icon:"☀️",theme_color:"#F97316",type:"Wisdom",rarity:"Uncommon",rarity_stars:2,emotional_power:46,wisdom_cost:2,quote:"The strongest warrior kneels — not from weakness, but from knowing their power.",reflection_prompt:"How do you balance believing in yourself with staying open to learning?",art_direction:"Balanced form, strong but bowed — confidence and humility in harmony"},
  {id:"MFP-022",name:"The Lens",chapter:8,chapter_title:"The Advantage of the Optimistic Mind",triptych_role:"A",triptych_role_name:"Concept",theme:"Fulfillment",theme_icon:"🌿",theme_color:"#22C55E",type:"Wisdom",rarity:"Common",rarity_stars:1,emotional_power:30,wisdom_cost:1,quote:"The optimist and the pessimist see the same world — one chooses to build in it.",reflection_prompt:"How do you typically interpret setbacks — as endings or as redirections?",art_direction:"Lens-shaped form, refracting light through parametric curves"},
  {id:"MFP-023",name:"The Cynic",chapter:8,chapter_title:"The Advantage of the Optimistic Mind",triptych_role:"B",triptych_role_name:"Challenge",theme:"Fulfillment",theme_icon:"🌿",theme_color:"#22C55E",type:"Reflection",rarity:"Common",rarity_stars:1,emotional_power:28,wisdom_cost:1,quote:"What have you stopped believing is possible?",reflection_prompt:"What dream did you once have that you've quietly given up on? Is it truly gone?",art_direction:"Curves dimming, cynical, tightening — the light fading"},
  {id:"MFP-024",name:"The Architect",chapter:8,chapter_title:"The Advantage of the Optimistic Mind",triptych_role:"C",triptych_role_name:"Transcendence",theme:"Fulfillment",theme_icon:"🌿",theme_color:"#22C55E",type:"Theme",rarity:"Uncommon",rarity_stars:2,emotional_power:48,wisdom_cost:2,quote:"An optimistic mind is not naive — it is the architect of impossible outcomes.",reflection_prompt:"What 'impossible' thing have you made happen through sheer belief and effort?",art_direction:"Expansive blueprint-like curves, constructing, building outward — the optimistic architect"},
  {id:"MFP-025",name:"The Hunger",chapter:9,chapter_title:"A Self-Fulfilled Life is Tantamount to Happiness",triptych_role:"A",triptych_role_name:"Concept",theme:"Fulfillment",theme_icon:"🍃",theme_color:"#00CED1",type:"Wisdom",rarity:"Common",rarity_stars:1,emotional_power:32,wisdom_cost:1,quote:"Fulfillment is not the destination — it is the way you walk the path.",reflection_prompt:"What does a fulfilled day look like for you? Did today come close?",art_direction:"Reaching, searching curves — hunger for meaning, seeking"},
  {id:"MFP-026",name:"The Comparison",chapter:9,chapter_title:"A Self-Fulfilled Life is Tantamount to Happiness",triptych_role:"B",triptych_role_name:"Challenge",theme:"Fulfillment",theme_icon:"🍃",theme_color:"#00CED1",type:"Reflection",rarity:"Uncommon",rarity_stars:2,emotional_power:40,wisdom_cost:2,quote:"Whose life are you measuring yours against, and why?",reflection_prompt:"When you feel 'not enough,' whose standard are you using? Is it even yours?",art_direction:"Curves splitting into parallel lines — comparison, measuring against others"},
  {id:"MFP-027",name:"The Harvest",chapter:9,chapter_title:"A Self-Fulfilled Life is Tantamount to Happiness",triptych_role:"C",triptych_role_name:"Transcendence",theme:"Fulfillment",theme_icon:"🍃",theme_color:"#00CED1",type:"Poem",rarity:"Rare",rarity_stars:3,emotional_power:56,wisdom_cost:3,quote:"I planted seeds in seasons of doubt and harvested meaning from every storm.",reflection_prompt:"What have you invested in that is now bearing fruit in your life?",art_direction:"Abundant, harvest-like forms, curves overflowing with fullness and abundance"},
  {id:"MFP-028",name:"The Dormant",chapter:10,chapter_title:"Attaining Our Highest Potentials",triptych_role:"A",triptych_role_name:"Concept",theme:"Potential",theme_icon:"🎯",theme_color:"#60A5FA",type:"Wisdom",rarity:"Common",rarity_stars:1,emotional_power:34,wisdom_cost:1,quote:"Your highest potential sleeps inside you, waiting for the courage to wake it.",reflection_prompt:"What talent or ability do you have that you haven't fully developed yet?",art_direction:"Dormant coiled form, potential energy stored, compressed curves"},
  {id:"MFP-029",name:"The Ceiling",chapter:10,chapter_title:"Attaining Our Highest Potentials",triptych_role:"B",triptych_role_name:"Challenge",theme:"Potential",theme_icon:"🎯",theme_color:"#60A5FA",type:"Reflection",rarity:"Common",rarity_stars:1,emotional_power:30,wisdom_cost:1,quote:"What limit have you accepted that was never yours to carry?",reflection_prompt:"Who told you that you couldn't? Do you still believe them?",art_direction:"Curves pressing against a visible ceiling, compressed, constrained"},
  {id:"MFP-030",name:"The Unleashed",chapter:10,chapter_title:"Attaining Our Highest Potentials",triptych_role:"C",triptych_role_name:"Transcendence",theme:"Potential",theme_icon:"🎯",theme_color:"#60A5FA",type:"Theme",rarity:"Epic",rarity_stars:4,emotional_power:82,wisdom_cost:4,quote:"Potential realized is not a destination — it is an explosion with no end.",reflection_prompt:"What would your life look like if you operated at full capacity? What's stopping you?",art_direction:"Explosive burst, curves radiating in all directions — potential unleashed"},
  {id:"MFP-031",name:"The Scale",chapter:11,chapter_title:"Equality Holds Peace and Justice",triptych_role:"A",triptych_role_name:"Concept",theme:"Equality",theme_icon:"⚖️",theme_color:"#9370DB",type:"Wisdom",rarity:"Common",rarity_stars:1,emotional_power:30,wisdom_cost:1,quote:"Equality is not sameness — it is the recognition that every soul carries the same weight.",reflection_prompt:"Where in your life do you practice true equality? Where do you fall short?",art_direction:"Balanced scale-like form, equal curves on each side — perfect symmetry"},
  {id:"MFP-032",name:"The Injustice",chapter:11,chapter_title:"Equality Holds Peace and Justice",triptych_role:"B",triptych_role_name:"Challenge",theme:"Equality",theme_icon:"⚖️",theme_color:"#9370DB",type:"Reflection",rarity:"Uncommon",rarity_stars:2,emotional_power:42,wisdom_cost:2,quote:"Where in your world do you see imbalance, and what can you do about it?",reflection_prompt:"What injustice have you witnessed recently? What small action could you take?",art_direction:"Tilted, asymmetric curves — injustice, imbalance visible"},
  {id:"MFP-033",name:"The Bridge",chapter:11,chapter_title:"Equality Holds Peace and Justice",triptych_role:"C",triptych_role_name:"Transcendence",theme:"Equality",theme_icon:"⚖️",theme_color:"#9370DB",type:"Theme",rarity:"Rare",rarity_stars:3,emotional_power:54,wisdom_cost:3,quote:"Justice built on equality does not bend — it holds the weight of all who cross.",reflection_prompt:"How can you be a bridge between people who see the world differently?",art_direction:"Bridge form, curves connecting two sides, balanced and strong"},
  {id:"MFP-034",name:"The Grudge",chapter:12,chapter_title:"Forgiveness is the Most Effective Solution",triptych_role:"A",triptych_role_name:"Concept",theme:"Forgiveness",theme_icon:"💧",theme_color:"#06B6D4",type:"Wisdom",rarity:"Common",rarity_stars:1,emotional_power:28,wisdom_cost:1,quote:"Unforgiveness is a poison you drink hoping the other person suffers.",reflection_prompt:"Is there someone you need to forgive — not for them, but for your own freedom?",art_direction:"Tight, knotted curves — a grudge held, tension visible"},
  {id:"MFP-035",name:"The Scar",chapter:12,chapter_title:"Forgiveness is the Most Effective Solution",triptych_role:"B",triptych_role_name:"Challenge",theme:"Forgiveness",theme_icon:"💧",theme_color:"#06B6D4",type:"Reflection",rarity:"Uncommon",rarity_stars:2,emotional_power:44,wisdom_cost:2,quote:"Who have you not forgiven — and what is it costing you to hold on?",reflection_prompt:"What would change in your life if you truly let go of one grudge today?",art_direction:"Scarred curves with sharp edges — pain that hasn't healed"},
  {id:"MFP-036",name:"The Release",chapter:12,chapter_title:"Forgiveness is the Most Effective Solution",triptych_role:"C",triptych_role_name:"Transcendence",theme:"Forgiveness",theme_icon:"💧",theme_color:"#06B6D4",type:"Poem",rarity:"Rare",rarity_stars:3,emotional_power:58,wisdom_cost:3,quote:"I open my hands and let the weight fall — I was never meant to carry your burden.",reflection_prompt:"Write a letter of forgiveness you never have to send. What would it say?",art_direction:"Curves opening, releasing, like hands letting go — water flowing free"},
  {id:"MFP-037",name:"The Reflection",chapter:13,chapter_title:"Accountability is a Must",triptych_role:"A",triptych_role_name:"Concept",theme:"Accountability",theme_icon:"🛡️",theme_color:"#EA580C",type:"Wisdom",rarity:"Common",rarity_stars:1,emotional_power:36,wisdom_cost:2,quote:"Accountability begins the moment you stop pointing at the world and point at yourself.",reflection_prompt:"What is one area of your life where you could take more ownership?",art_direction:"Mirror-like reflective curves — self-examination, facing oneself"},
  {id:"MFP-038",name:"The Excuse",chapter:13,chapter_title:"Accountability is a Must",triptych_role:"B",triptych_role_name:"Challenge",theme:"Accountability",theme_icon:"🛡️",theme_color:"#EA580C",type:"Reflection",rarity:"Common",rarity_stars:1,emotional_power:30,wisdom_cost:1,quote:"What story are you telling yourself to avoid taking responsibility?",reflection_prompt:"What excuse have you been making that, deep down, you know isn't true?",art_direction:"Loose, drifting curves — excuses, lack of direction"},
  {id:"MFP-039",name:"The Anchor",chapter:13,chapter_title:"Accountability is a Must",triptych_role:"C",triptych_role_name:"Transcendence",theme:"Accountability",theme_icon:"🛡️",theme_color:"#EA580C",type:"Theme",rarity:"Uncommon",rarity_stars:2,emotional_power:50,wisdom_cost:3,quote:"The accountable soul does not drift — it is anchored to its own word.",reflection_prompt:"What promise have you made to yourself that you've kept? How did it feel?",art_direction:"Anchor-like form, grounded, solid, immovable — accountability embodied"},
  {id:"MFP-040",name:"The Morning",chapter:14,chapter_title:"Today is the First Day of Your Life",triptych_role:"A",triptych_role_name:"Concept",theme:"Today",theme_icon:"🌅",theme_color:"#FBBF24",type:"Wisdom",rarity:"Common",rarity_stars:1,emotional_power:32,wisdom_cost:1,quote:"Today is the only day that exists. Yesterday is memory. Tomorrow is imagination.",reflection_prompt:"If today were your very first day alive, what would you notice for the first time?",art_direction:"Soft morning light curves, awakening, fresh and new"},
  {id:"MFP-041",name:"The Regret",chapter:14,chapter_title:"Today is the First Day of Your Life",triptych_role:"B",triptych_role_name:"Challenge",theme:"Today",theme_icon:"🌅",theme_color:"#FBBF24",type:"Reflection",rarity:"Uncommon",rarity_stars:2,emotional_power:38,wisdom_cost:2,quote:"What would you do differently if today were truly your first day?",reflection_prompt:"What regret from the past is stealing energy from your present?",art_direction:"Curves pulled backward, looking over their shoulder — regret, dwelling"},
  {id:"MFP-042",name:"The Present",chapter:14,chapter_title:"Today is the First Day of Your Life",triptych_role:"C",triptych_role_name:"Transcendence",theme:"Today",theme_icon:"🌅",theme_color:"#FBBF24",type:"Poem",rarity:"Rare",rarity_stars:3,emotional_power:62,wisdom_cost:3,quote:"I stand at the beginning of everything — the past has released me, the future awaits my command.",reflection_prompt:"What would you create, start, or change if you truly believed today was day one?",art_direction:"Curves facing forward, radiant, present, NOW — full sunrise, total presence"},
  {id:"MFP-043",name:"The Journey",chapter:15,chapter_title:"Life is Longest",triptych_role:"A",triptych_role_name:"Concept",theme:"Life",theme_icon:"🌍",theme_color:"#84CC16",type:"Wisdom",rarity:"Uncommon",rarity_stars:2,emotional_power:40,wisdom_cost:2,quote:"Life is the longest thing you will ever do — treat it with the reverence it demands.",reflection_prompt:"If life is a marathon not a sprint, where are you in the race? Are you pacing well?",art_direction:"A path beginning, simple curves stepping forward — the journey starts"},
  {id:"MFP-044",name:"The Weariness",chapter:15,chapter_title:"Life is Longest",triptych_role:"B",triptych_role_name:"Challenge",theme:"Life",theme_icon:"🌍",theme_color:"#84CC16",type:"Reflection",rarity:"Uncommon",rarity_stars:2,emotional_power:40,wisdom_cost:2,quote:"When the road feels endless, what gives you the strength to take one more step?",reflection_prompt:"What do you do when you feel like giving up? What keeps you going?",art_direction:"Heavy, weary curves — the long road, endurance tested"},
  {id:"MFP-045",name:"The Eternal",chapter:15,chapter_title:"Life is Longest",triptych_role:"C",triptych_role_name:"Transcendence",theme:"Life",theme_icon:"🌍",theme_color:"#84CC16",type:"Legendary",rarity:"Legendary",rarity_stars:5,emotional_power:95,wisdom_cost:5,quote:"I am the sum of every step, every fall, every rise — life is longest, and I have made it beautiful.",reflection_prompt:"If you could tell your younger self one thing about the journey so far, what would it be?",art_direction:"ALL previous chapter colors blended into one magnificent form — the sum of everything, the most complex and beautiful form of all 15 triptychs. The capstone."},
];

/** Get cards by chapter number */
export function getCardsByChapter(chapter: number): Card[] {
  return CARDS.filter(c => c.chapter === chapter);
}

/** Get cards by rarity */
export function getCardsByRarity(rarity: Card['rarity']): Card[] {
  return CARDS.filter(c => c.rarity === rarity);
}

/** Get cards by type */
export function getCardsByType(type: Card['type']): Card[] {
  return CARDS.filter(c => c.type === type);
}

/** Get chapter info */
export function getChapter(number: number): Chapter | undefined {
  return CHAPTERS.find(c => c.number === number);
}
